language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - rbx-18mode
  - jruby-19mode
  - jruby-18mode
script: 'bundle exec rake'
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: rbx-18mode
